Homework
Independent-Agency-Alliance/automation-training pull request #2
Opened 2024-01-09 08:17 UTC by NhuyNhuy63

2024-01-10 03:46 UTC, liamnguyeniaa requested changes
comments

2024-01-10 03:46 UTC, liamnguyeniaa commented on src/02-ttts2023-agu-pagination-nhi-le.test.js
> +    const pagination = Selector(".main .page-item .page-link").nth(2);
page2Button

2024-01-10 03:46 UTC, liamnguyeniaa commented on src/02-ttts2023-agu-pagination-nhi-le.test.js
> +    const firsttext = Selector(".main .container .blog-details >h5 >a");
revise this selector

2024-01-10 03:46 UTC, liamnguyeniaa commented on src/02-ttts2023-agu-pagination-nhi-le.test.js
> +    const firsttext = Selector(".main .container .blog-details >h5 >a");
firstPostTitle

2024-01-10 03:46 UTC, liamnguyeniaa commented on src/02-ttts2023-agu-pagination-nhi-le.test.js
> +    const FirstText = await firsttext.textContent;
firstPostTitleContent

2024-01-10 03:46 UTC, liamnguyeniaa commented on src/02-ttts2023-agu-pagination-nhi-le.test.js
> +    const secondtext = Selector(".main .container .blog-details >h5 >a");
firstPostTitleOnPage2

2024-01-10 03:46 UTC, liamnguyeniaa commented on src/02-ttts2023-agu-pagination-nhi-le.test.js
> +    const secondtext = Selector(".main .container .blog-details >h5 >a");
revise the selector

2024-01-15 03:18 UTC, liamnguyeniaa requested changes
only minor comments left

2024-01-15 03:18 UTC, liamnguyeniaa commented on src/02-ttts2023-agu-pagination-nhi-le.test.js
> +    await t.expect(firstPostTitleContent).notEql(firstPostTitleOnPage2Content);
Need to test the next and prev button as well.

2024-01-17 03:14 UTC, tvteo approved these changes

2024-01-17 03:14 UTC, NhuyNhuy63 commented on src/02-ttts2023-agu-pagination-nhi-le.test.js
> +    const pagination = Selector(".main .page-item .page-link").nth(2);
done

2024-01-17 03:15 UTC, NhuyNhuy63 commented on src/02-ttts2023-agu-pagination-nhi-le.test.js
> +    const firsttext = Selector(".main .container .blog-details >h5 >a");
done

2024-01-17 03:15 UTC, NhuyNhuy63 commented on src/02-ttts2023-agu-pagination-nhi-le.test.js
> +    const FirstText = await firsttext.textContent;
done

2024-01-17 03:15 UTC, NhuyNhuy63 commented on src/02-ttts2023-agu-pagination-nhi-le.test.js
> +    const secondtext = Selector(".main .container .blog-details >h5 >a");
done

2024-01-17 03:15 UTC, NhuyNhuy63 commented on src/02-ttts2023-agu-pagination-nhi-le.test.js
> +    const firsttext = Selector(".main .container .blog-details >h5 >a");
done

2024-01-22 03:16 UTC, liamnguyeniaa approved these changes

2024-01-22 03:16 UTC, merged