homework
Independent-Agency-Alliance/automation-training pull request #5
Opened 2024-01-09 14:45 UTC by nthikimngoc

2024-01-10 03:49 UTC, liamnguyeniaa requested changes
comments

2024-01-10 03:49 UTC, liamnguyeniaa commented on src/homework-NN.js
review the comments left on Nhi's PR and add something different than Nhi's approach.

2024-01-15 03:11 UTC, liamnguyeniaa reviewed
1. Review variable naming
1. make sure the test case never end with action
2. fix all the comments.

2024-01-15 03:11 UTC, liamnguyeniaa commented on src/02-so2-ttts2023-agu-pagination-ngocnguyen.test.js
> +      .ok("At more six search result should exist");
incorrect message. 

need to validate that the pagination doesn't appear.

2024-01-15 03:11 UTC, liamnguyeniaa commented on src/02-so3-ttts2023-agu-pagination-ngocnguyen.test.js
> +  const ClickNextPage = Selector(".main .page-item:last-child .page-link");
incorrect variable name. use camelCase.

2024-01-15 03:11 UTC, liamnguyeniaa commented on src/02-so3-ttts2023-agu-pagination-ngocnguyen.test.js
> +    .ok("At more six search result should exist");
incorrect message

2024-01-15 03:11 UTC, liamnguyeniaa commented on src/02-so3-ttts2023-agu-pagination-ngocnguyen.test.js
> +  for (let i = 0; i < 5; i++) {
there are only 2 pages. Why do we need to click 5 times?

2024-01-15 03:11 UTC, liamnguyeniaa commented on src/02-so3-ttts2023-agu-pagination-ngocnguyen.test.js
> +  await t.click(ClickPreviousPage);
the test case should never end with action.

2024-01-15 03:11 UTC, liamnguyeniaa commented on src/02-ttts2023-agu-pagination-ngocnguyen.test.js
> +  const ClickNextPage = Selector(".main .page-item:last-child .page-link");
incorrect variable name.

2024-01-16 11:53 UTC, nthikimngoc commented on src/02-ttts2023-agu-pagination-ngocnguyen.test.js
> +  const ClickNextPage = Selector(".main .page-item:last-child .page-link");
Done

2024-01-16 11:53 UTC, nthikimngoc commented on src/02-ttts2023-agu-pagination-ngocnguyen.test.js
> +  const ClickNextPage = Selector(".main .page-item:last-child .page-link");
Done

2024-01-22 03:20 UTC, merged